### ISSUE TITLE
Access token error

### ISSUE THREAD

**Issue by WilliamCrockett** [starkillerOG/motion-blinds#25]
Hi, 

Last night my CMD-01 bridge lost power and restarted. This morning I noticed I have no control of my blinds from HA, and that the bridge was flashing green, which the manual says stands for "bridge firmware update". 

When I started looking at the logs, etc, I noticed that there is an error with the heading AccessToken error. I will copy the full text below. 

The integration has been working flawlessly until this happened. So I am wondering if my firmware of my CMD-01 did infact update and this has caused an issue? according to the Motion app, my firmware version is: A1.0.5_B0.1.6, there is also no update available for the firmware. 

Obviously, this could be unrelated, but I am hoping someone could help guide me into solving this problem? 

Many thanks

Error text: 

`Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '500291d0b4cd0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220623124125219', 'data': {'operation': 0}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '500291d0b4cd0001', 'deviceType': '10000000', 'msgID': '20220623144121537', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'`

Additional info: 

`Logger: motionblinds.motion_blinds
Source: /usr/local/lib/python3.9/site-packages/motionblinds/motion_blinds.py:504`

**Comment by rjulius23** [comment]
We are facing the same issue from multiple users. Will get the firmware versions.

**Comment by bocsitomcsi** [comment]
Yep the same happened in our case with HomeAssisstatn.

Firmware version: A1.0.3_B0.1.2

I have checked with python interpreter and recieved the very same issue:

```
>>> for blind in m.device_list.values():
...   blind.Update()
...   print(blind)
...
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220624114813499', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220624134812705', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220624114818536', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220624134817724', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220624114823555', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220624134822842', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220624114828670', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220624134827879', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220624114833729', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220624134832980', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 1241, in Update
    mcast_response = self._wait_on_mcast_report(mcast)
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 974, in _wait_on_mcast_report
    mcast_data, (ip, _) = mcast_socket.recvfrom(SOCKET_BUFSIZE)
socket.timeout: timed out
```

With that I think something has been changed with the new firmware.

Hardware: DD 7002 B bridge

**Comment by bocsitomcsi** [comment]
One more thing that maybe can help or maybe just bring more noise :D

We have two sites where we have identically the same DD 7002 B bridge with the very same firmware with the very same setup

```
#First System
<MotionGateway ip: 192.168.0.19, mac: 34ab958ddb9c, protocol: 0.9, firmware: A1.0.3_B0.1.2, N_devices: 11, status: Working, RSSI: -33 dBm>

#Second System (faulty)
<MotionGateway ip: 192.168.8.103, mac: 246f28444c1c, protocol: 0.9, firmware: A1.0.3_B0.1.2, N_devices: 15, status: Working, RSSI: -24 dBm>
```

I have used the very same version of motion blind python (0.6.4 and also tried with 0.6.8) version.

With the first bridge we have managed to gather the devices while with the second one it fails with the above issue. The biggest change that first one is running since 2-3 month without any restart while the second just powered up yesterday (2022-06-23).

I have realised that the token value is the very same for both of the system:
```
>>> print(m.token)
967DC7CD55376DA9
```

Can it be that this token is outdated or overtimed and that cause the issue?

**Comment by PRoomberg** [comment]
> Last night my CMD-01 bridge lost power and restarted. This morning I noticed I have no control of my blinds from HA, and that the bridge was flashing green, which the manual says stands for "bridge firmware update".

This has happend to my CMD-01 bridge more than once. The only way to resolve it and get it working again is resetting the bridge and adding all blinds back. :-(
Now the bridge is plugged into an UPS.

**Comment by WilliamCrockett** [comment]
> > Last night my CMD-01 bridge lost power and restarted. This morning I noticed I have no control of my blinds from HA, and that the bridge was flashing green, which the manual says stands for "bridge firmware update".
> 
> 
> 
> This has happend to my CMD-01 bridge more than once. The only way to resolve it and get it working again is resetting the bridge and adding all blinds back. :-(
> 
> Now the bridge is plugged into an UPS.

Thanks. I did that thinking it would resolve the issue, but unfortunately it did not... 😕

**Comment by starkillerOG** [comment]
I was on vacation, so red this only now.
I do not have any problems on my own system, but I am using a CM-20 bridge instead of the mini.

@rjulius23 Do you work for a company manufacturing smart blinds? (since you said multiple users?)

@bocsitomcsi are you sure the key is the same for both systems?

This unfortunately seems to be a firmware issue, I will discuss it with the manufacturer.

I will also add an aditional check if the token might have changed (from the error response) but I guess that is not the case.

**Comment by EDelsman** [comment]
I checked for two cases, my own and some one else. Verified the key, verified the token. Even checked the key/token combination with the procedure from the documentation. It all checkes out, but the bridge no longer accepts it.

**Comment by bocsitomcsi** [comment]
@starkillerOG I hope you had a great vacation and welcome back

The key is different but the token is the same, maybe it is device specific.

I did some further check based on this documentation: https://github.com/alexbacchin/ConnectorBridge

And what makes really hard to understand - at least for me - that I have managed to get information about the controller and even the devices type and numbers. But when I try to gather information about the devices like the above mentioned way I get the access token error. Based on my understanding for this sequence I would also need access token:

```
>>> from motionblinds import MotionGateway
>>> m = MotionGateway(ip = "192.168.8.103", key = "53579a56-2127-45")
>>> m.GetDeviceList()
{'246f28444c1c0001': <MotionBlind mac: 246f28444c1c0001, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0002': <MotionBlind mac: 246f28444c1c0002, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0003': <MotionBlind mac: 246f28444c1c0003, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0004': <MotionBlind mac: 246f28444c1c0004, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0005': <MotionBlind mac: 246f28444c1c0005, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0006': <MotionBlind mac: 246f28444c1c0006, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0007': <MotionBlind mac: 246f28444c1c0007, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0008': <MotionBlind mac: 246f28444c1c0008, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0009': <MotionBlind mac: 246f28444c1c0009, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000a': <MotionBlind mac: 246f28444c1c000a, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000b': <MotionBlind mac: 246f28444c1c000b, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000c': <MotionBlind mac: 246f28444c1c000c, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000d': <MotionBlind mac: 246f28444c1c000d, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000f': <MotionBlind mac: 246f28444c1c000f, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0010': <MotionBlind mac: 246f28444c1c0010, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>}
>>> m.Update()
>>> print(m.status)
Working
>>> print(m)
<MotionGateway ip: 192.168.8.103, mac: 246f28444c1c, protocol: 0.9, firmware: A1.0.3_B0.1.2, N_devices: 15, status: Working, RSSI: -24 dBm>
>>> for blind in m.device_list.values():
...   blind.Update()
...   print(blind)
...
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': '56FB39FF53279C382A5B2AF3DF9B2A82', 'msgID': '20220628201534884', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220628221533793', 'token': '967DC7CD55376DA9', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': '56FB39FF53279C382A5B2AF3DF9B2A82', 'msgID': '20220628201539917', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220628221538933', 'token': '967DC7CD55376DA9', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': '56FB39FF53279C382A5B2AF3DF9B2A82', 'msgID': '20220628201545055', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220628221544032', 'token': '967DC7CD55376DA9', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': '56FB39FF53279C382A5B2AF3DF9B2A82', 'msgID': '20220628201550155', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220628221549153', 'token': '967DC7CD55376DA9', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': '56FB39FF53279C382A5B2AF3DF9B2A82', 'msgID': '20220628201555276', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220628221554278', 'token': '967DC7CD55376DA9', 'actionResult': 'AccessToken error'}'
Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 1225, in Update
    mcast_response = self._wait_on_mcast_report(mcast)
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 960, in _wait_on_mcast_report
    mcast_data, (ip, _) = mcast_socket.recvfrom(SOCKET_BUFSIZE)
socket.timeout: timed out
```

**Comment by WilliamCrockett** [comment]
Hi @starkillerOG , thanks for getting back to me here. 

I have pip installed the package and attempted to run it locally and try debug the issue. So far no head way. But please let me know if there's anything I can provide you to help the debugging. 

Many thanks
William

**Comment by starkillerOG** [comment]
@bocsitomcsi The `m.GetDeviceList()` does not require and does not use the AccesToken, so that makes sense.
The `m.Update()` actually does not require the AccesToken, however it is sent as part of the message, this is because in some firmware version there was a change in which the AccesToken was required all of a sudden for the `m.Update()`, then in a latter firmware version they reverted that behaviour after I told them and now it is again not required. However sending the AccesToken when not required is allowed and is backwards compatible with all versions of the firmware as far as I am aware.

blind.Update() does require the AccesToken so in that way it makes sense.

**Comment by starkillerOG** [comment]
@bocsitomcsi what version of motionblinds are you using? the accestoken en token schould have been obscured as xxxxx in the logs for the latest motionblinds versions (security risk). In general it is not a good idea to post accestokens publicly on the internet....

**Comment by starkillerOG** [comment]
I just released version 0.6.9 of the motionblinds library which add a check if the token has changed when a AccesToken error is received.

Could someone update using `pip3 install --upgrade motionblinds` and test the python script again to see if you get some `Gateway token has changed from actionResult` warning?

**Comment by bocsitomcsi** [comment]
Thanks for the clarification it makes sense, then the very first moment when we need really the accesstoken is the blind.Updates() part.

I have removed the accesstoken from the above comment thanks for highlighting it. I have not realised that it has been printed out. I have reverted back to 0.6.4 version, the one that is used by HomeAssisstant 2022.4.x as well.

I have updated to 0.6.8 version and recieved the same error:

```
>>> for blind in m.device_list.values():
...   blind.Update()
...   print(blind)
...
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629105754496', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629125753324', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629105759519', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629125758444', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629105804638', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629125803564', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629105809758', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629125808684', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629105818740', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629125817659', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 1241, in Update
    mcast_response = self._wait_on_mcast_report(mcast)
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 974, in _wait_on_mcast_report
    mcast_data, (ip, _) = mcast_socket.recvfrom(SOCKET_BUFSIZE)
socket.timeout: timed out

```

**Comment by bocsitomcsi** [comment]
@starkillerOG yes I can confirm that I see the warning message

```
>>> for blind in m.device_list.values():
...   blind.Update()
...   print(blind)
...
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629110115256', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629130114131', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
**Gateway token has changed from actionResult.**
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629110120328', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629130119251', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629110125447', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629130124371', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629110130562', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629130129388', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629110135585', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629130134508', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Timeout of 5.0 sec occurred on 5 attempts while waiting on multicast push from update request, communication between gateway and blind might be bad.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 1247, in Update
    mcast_response = self._wait_on_mcast_report(mcast)
  File "/home/yabutech/.local/lib/python3.7/site-packages/motionblinds/motion_blinds.py", line 980, in _wait_on_mcast_report
    mcast_data, (ip, _) = mcast_socket.recvfrom(SOCKET_BUFSIZE)
socket.timeout: timed out

```

**Comment by WilliamCrockett** [comment]
@starkillerOG I am getting it too with my CMD-01

**Comment by starkillerOG** [comment]
Alright that is really weared, could someone run the following python code and report all output (all warnings etc):
Note that this script will print the token of your gateway, so beware if you do not want to share that you can mask them but check very carefully if the two tokens that are printed are exactly identicall or not and tell me that.

```
from motionblinds import MotionGateway
m = MotionGateway(ip = "192.168.1.IP", key = "?????????")
m.GetDeviceList()
m.Update()
blind_1 = list(m.device_list.values())[0]
print("token before blind update")
print(m.token)
blind_1.Update_trigger()
print("token after blind update")
print(m.token)
print("second update try")
blind_1.Update_trigger()
```

**Comment by bocsitomcsi** [comment]
```
>>> from motionblinds import MotionGateway
>>> m = MotionGateway(ip = "192.168.8.103", key = "53579a56-2127-45")
>>> m.GetDeviceList()
{'246f28444c1c0001': <MotionBlind mac: 246f28444c1c0001, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0002': <MotionBlind mac: 246f28444c1c0002, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0003': <MotionBlind mac: 246f28444c1c0003, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0004': <MotionBlind mac: 246f28444c1c0004, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0005': <MotionBlind mac: 246f28444c1c0005, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0006': <MotionBlind mac: 246f28444c1c0006, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0007': <MotionBlind mac: 246f28444c1c0007, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0008': <MotionBlind mac: 246f28444c1c0008, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0009': <MotionBlind mac: 246f28444c1c0009, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000a': <MotionBlind mac: 246f28444c1c000a, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000b': <MotionBlind mac: 246f28444c1c000b, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000c': <MotionBlind mac: 246f28444c1c000c, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000d': <MotionBlind mac: 246f28444c1c000d, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c000f': <MotionBlind mac: 246f28444c1c000f, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>, '246f28444c1c0010': <MotionBlind mac: 246f28444c1c0010, type: None, status: None, position: None %, angle: None, limit: None, battery: None, None %, None V, RSSI: None dBm, com: None>}
>>> m.Update()
>>> blind_1=list(m.device_list.values())[0]
>>> print("token before blind update")
token before blind update
>>> print(m.token)
967DC7CD5XXXXXXX
>>> blind_1.Update_trigger()
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629112506843', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629132505684', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
Gateway token has changed from actionResult.
>>> print("token after blind update")
token after blind update
>>> print(m.token)
xxxxxxxxxxxxxxxx
>>> print("second update try")
second update try
>>> blind_1.Update_trigger()
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629112535645', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '246f28444c1c0001', 'deviceType': '10000000', 'msgID': '20220629132534459', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'

```

**Comment by starkillerOG** [comment]
Alright found one bug: the log_hide function was altering the actual response.
I just published 0.6.10, could you update again using `pip3 install --upgrade motionblinds` and run the above script again?

**Comment by starkillerOG** [comment]
Thanks @WilliamCrockett that indeed confirms the token stays the same, so that is not the problem.
It really looks like some internal firmware issue where it is not accepting the AccesToken while it is correct.
Maybe somehow the internal key has changed withouth the app showing a diffrent key.

You have checked the key in the app right? that is still identical to the one you use for this python script right?
The app is still able to control the blinds? (Move up and down)?
Maybe move the blinds in the app and then check the key of the app again?

**Comment by starkillerOG** [comment]
We can also look if the gateway also refuses moving the blind:
Note that this will move your first blind in the list to 60%

```
from motionblinds import MotionGateway
m = MotionGateway(ip = "192.168.1.IP", key = "?????????")
m.GetDeviceList()
m.Update()
blind_1 = list(m.device_list.values())[0]
blind_1.Set_position(60)
```

**Comment by WilliamCrockett** [comment]
@starkillerOG 

yes, the key in the app is still the same and has not changed. So yes, maybe internal key has changed. 

I wonder if I should try create a new account, and link the CMD-01 to that account, and re-link the blinds, and see what happens... 

I have full control of the blinds through the app, and have been using the motion app to control my blinds for a few days now, the key hasn't changed. 

I tried logging out and back in, and the key is still the same!

**Comment by WilliamCrockett** [comment]
> We can also look if the gateway also refuses moving the blind: Note that this will move your first blind in the list to 60%
> 
> ```
> from motionblinds import MotionGateway
> m = MotionGateway(ip = "192.168.1.IP", key = "?????????")
> m.GetDeviceList()
> m.Update()
> blind_1 = list(m.device_list.values())[0]
> blind_1.Set_position(60)
> ```

just ran this and received same error: 

```
Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '500291d0b4cd0001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20220629115348643', 'data': {'targetPosition': 60}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '500291d0b4cd0001', 'deviceType': '10000000', 'msgID': '20220629135337042', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
```

**Comment by NNMavy** [comment]
I just got off the phone with the manufacturer due to this very issue. They claim there is a bug in the hardware of the CMD-01 that cannot be resolved by a firmware update and they are sending me a new hub.

I read similar stories in both product reviews and tech forums and everyone who recieved a new hub say this seems to have fixed the issue.

**Comment by starkillerOG** [comment]
@ConnectorGit Do you know anything more about this "hardware bug"?

**Comment by PRoomberg** [comment]
Who can we contact about a replacement? And what details do they need? 
Would love to get rid of the reset and reconnect bug.

**Comment by WilliamCrockett** [comment]
I just paired my bridge to a whole new motion account, with a new key, and I get the same issue - AccessToken error. What I do notice, however, is that even with the new key, my 'token' is still the same as when I had it paired on the old account.

**Comment by heyryan29** [comment]
> I just paired my bridge to a whole new motion account, with a new key, and I get the same issue - AccessToken error.
> 
> edit - yes of course it's the same. Apologies

Hi William,

I'm part of the development team, it seems something went wrong with the bridge itself, could you please provide your APP account (no password required) and send 'Feedback' when your bridge is online (LED solid blue). I'd like to check the details of your hub to see what happened. It may help us figure out the root cause.  

It may help to reset the bridge (long press 10 seconds) before pairing it again. Reset the bridge, pair it, add blinds to the bridge, and then link to HA.

**Comment by EDelsman** [comment]
> > I just paired my bridge to a whole new motion account, with a new key, and I get the same issue - AccessToken error.
> > edit - yes of course it's the same. Apologies
> 
> Hi William,
> 
> I'm part of the development team, it seems something went wrong with the bridge itself, could you please provide your APP account (no password required) and send 'Feedback' when your bridge is online (LED solid blue). I'd like to check the details of your hub to see what happened. It may help us figure out the root cause.
> 
> It may help to reset the bridge (long press 10 seconds) before pairing it again. Reset the bridge, pair it, add blinds to the bridge, and then link to HA.

Hi @heyryan29 ,

I have the same problems, and being the developer for the Homey app I also did quite some investigation, so I'll be glad to help too. Over the past year I did numerous resets during development, but the one I did last weekend lead to these problems. I also noticed the reset did give the red blinking, followed by pairing mode, but then was not fully reset in the sense that when pairing new blinds, the mac addresses do not start numbering at one as they did before, but continue where they would have before the reset.

I tried removing the bridge from the account before the reset, using a new account and all sorts of other things,  ut the result is always the same. I also put in a report just now, let me know if I can do anything to help.

**Comment by heyryan29** [comment]
> 

Hi @EDelsman ,

Thanks for sharing. Could you please provide me with your APP account, we'll check it.

Some updates here, this should not be the cause of the problem 'AccessToken error' discussed here, but I want to share some information that will cause the integration to fail.  

1. After a reset, the configurations of the bridge are removed including credentials and blinds info (blinds/devices, scenes, and timers). So if you'd like to link to HA, Homey, or others, you need to pair the bridge again to inject credentials. Otherwise you will encounter 'AccessToken error'.
2. Unpair the hub in the APP will also remove credentials in the bridge, so please don't unpair after linking to HA, Homey, etc. But note that if it's the same bridge you pair with the same account, credentials for UDP integration do not change no matter how many times you pair/unpair, you can still use the old AccessToken after pairing.

_'the mac addresses do not start numbering at one as they did before, but continue where they would have before the reset.'_
This is an expected action, LED starts blinking red after 10 secs of pressing indicates that the bridge has been reset.

**Comment by heyryan29** [comment]
> 

Hi @WilliamCrockett ,

We found some odd things, but unfortunately, some important records were overwritten, could you please unpair the bridge (it would be better if you can reset the bridge before), pair it with your APP account again, use HA to poll/control your blinds, and then 'feedback' again.

Many thanks.

**Comment by WilliamCrockett** [comment]
> > 
> 
> Hi @WilliamCrockett ,
> 
> We found some odd things, but unfortunately, some important records were overwritten, could you please unpair the bridge (it would be better if you can reset the bridge before), pair it with your APP account again, use HA to poll/control your blinds, and then 'feedback' again.
> 
> Many thanks.

Hi @heyryan29 

I have done this now. 

- I reset the bridge (it flashed red) 
- deleted it from motion app
- re paired 
- added a blind 
- connected it to HA 
- Tried to control the blind 
- sent feedback

thanks
William

**Comment by EDelsman** [comment]
@heyryan29: my account is a gmail account starting with sp.delsman+motion and the usual gmail things after.
The reason I mentioned the mac number behaviour is that this changed with the last firmware update, as did these problems, so there may be a relation.


Right now I'm happy to get it working at all, but I've needed to do quite a few resets/re-pair over time. Changing the macs for the blinds would force users to remove all blinds from Homey, breaking all automations with it. That never used to be the case before. If the bridge hang problems persist, that will cause major extra headache.

Usually when the bridge hangs (used to be flashing red/purple, with the newer firmware it was flashing yellow/green), there is no choice but to remove the hub from the app and reset it as they no longer communicate. An attempt to set wifi again would fail. But I'm 100% sure the accessToken is correct with the key from the app and the token I got from the bridge.

**Comment by heyryan29** [comment]
@EDelsman We now have a new firmware that improves the Wi-Fi connection performance (ver. A1.0.6_B0.1.6, not publicly released yet), I'm wondering if you'd like to have it. If yes, we can upload your bridge firmware to this new one. 

It's very important to Only query the motor status when necessary, DO NOT run a scheduled task to query the motor status, like every 10 minutes or even 1 minute. It will greatly improve the integration performance to avoid unexpected errors. 

1. It is recommended to query the motor status before controlling the motor, instead of schedule query tasks, so that the user can also get the motor status on the application control page; 
2. Whether the motor is controlled by your integration or other controllers, when the motor stops running, you will receive a position update message from the bridge, which you can use to refresh the motor state;
3. Motor MACs will be deleted after the bridge reset; 
4. Only re-pairing the bridge without reset the bridge, motor macs will not be deleted;

**Comment by heyryan29** [comment]
> > > 
> > 
> > 
> > Hi @WilliamCrockett ,
> > We found some odd things, but unfortunately, some important records were overwritten, could you please unpair the bridge (it would be better if you can reset the bridge before), pair it with your APP account again, use HA to poll/control your blinds, and then 'feedback' again.
> > Many thanks.
> 
> Hi @heyryan29
> 
> I have done this now.
> 
> * I reset the bridge (it flashed red)
> * deleted it from motion app
> * re paired
> * added a blind
> * connected it to HA
> * Tried to control the blind
> * sent feedback
> 
> thanks William

@WilliamCrockett Fixed a bug, now re-pairing the bridge with the same APP account can restore your HA integration control. If possible, could you share me with the HA applet link. I would like to discuss with the developer to avoid the schedule query task from HA side.

Would you like to try the new firmware ver. A1.0.6_B0.1.6  :-)

**Comment by WilliamCrockett** [comment]
> > > > 
> > > 
> > > 
> > > Hi @WilliamCrockett ,
> > > We found some odd things, but unfortunately, some important records were overwritten, could you please unpair the bridge (it would be better if you can reset the bridge before), pair it with your APP account again, use HA to poll/control your blinds, and then 'feedback' again.
> > > Many thanks.
> > 
> > 
> > Hi @heyryan29
> > I have done this now.
> > 
> > * I reset the bridge (it flashed red)
> > * deleted it from motion app
> > * re paired
> > * added a blind
> > * connected it to HA
> > * Tried to control the blind
> > * sent feedback
> > 
> > thanks William
> 
> @WilliamCrockett Fixed a bug, now re-pairing the bridge with the same APP account can restore your HA integration control. If possible, could you share me with the HA applet link. I would like to discuss with the developer to avoid the schedule query task from HA side.
> 
> Would you like to try the new firmware ver. A1.0.6_B0.1.6 :-)

Hi @heyryan29 

Thanks for the note. I'll be home this afternoon and will test it. 

I would guess it's probably beneficial for me to have the new firmware. What does it change/fix? 

I believe this repo is what is used by HA, and @starkillerOG is the developer for that. Alternatively, here's some additional links:

https://github.com/home-assistant/core/tree/dev/homeassistant/components/motion_blinds 
https://www.home-assistant.io/integrations/motion_blinds/

Many thanks for your help thus far

**Comment by EDelsman** [comment]
@heyryan29 : I would very much like to test the new firmware. Does it also solve the accessToken problems? 

In Homey I poll the blinds maybe once a day, and also if I do not get a report within a set timeframe. This is needed for several reasons: 

1: multicast is implemented in a way in the bridge that it does not work if IGMP snooping is active. But IGMP snooping cannot always be turned off if IP tv is used in the home, especially in the Netherlands, where e.g. KPN requires it. In that case reports do not come in.

2: Even when multicast works, reports do not always come in reliably. This happens most if an external remote controls more blinds simultaneously, but it also happens on single blind operations from the app.

**Comment by starkillerOG** [comment]
@heyryan29 I am the HomeAssistant developer and maintain both this library (which is the backbone of the HA integration) and the HA integration itself.
I would be more than happy to discuss with you possible improvements to the HA integration.
Can you share a e-mail adress, then I can send you my phone number?

In regards to the status querying: HomeAssistant works as a smart home platform not just as a user interface like the native Motion blinds app. As @EDelsman explained it is vital that the actual status of the motors keep in sync with HomeAssistant at all times (for automation purposes), relying soly on the UDP multicast messages is not relyable enough to keep the status in sync (foremost because UDP itself does not garantee messages actually come through, it does not guard against packet loss, besides there are countless problems with multicast like routers blocking it, diffrent VLANs, wrong bound interface etc).

That is why currently there is a status query to the blinds every 15 minutes in HA (also to monitor battery level during charging).

@heyryan29 why would status querying cause aditional errors?
Is it just because that increases the amount of API calls and therefore random errors like packet loss occur more often, because in that case we are not solving a problem by reducting querying. Those errors will then still occur at control commands like open/close in the same frequency.
Or is there some limited read/write operation on some EEPROM in the bridge?
Or are you worried about too many requests at the same time to the bridge?

**Comment by wmollenvanger** [comment]
I'm another victim of this; didn't notice before since my system was offline for a few weeks.

For what it's worth: the EVAL tool has the same AccessToken error on a WriteDevice message. Querying works normally. My shades are Brel and their app still works for some reason. I do see the version of the app is 1.2.0 (220530001) so it was updated recently....

**Comment by wmollenvanger** [comment]
> I noticed this morning I had the new firmware on my bridge

how do you access the bridge to check? Mine is just an usb stick with a led and 1 button, IP address of it doesn't respond to 80 or 443....

**Comment by starkillerOG** [comment]
@heyryan29 any updates on this?
Could you sent me your e-mail adress, would love to discuss what I could do to help from the library/homeassistant side of things.

**Comment by wmollenvanger** [comment]
@starkillerOG 

Thanks, can't find it in the brel app, don't think they have implemented it.

The HA integration shows 
"Wi-Fi bridge
door Motion Blinds, Coulisse B.V.
Firmware: Protocol: 0.9 "

**Comment by starkillerOG** [comment]
I just created a PR to implement a 1.5 second delay inbetween two update requests to different blinds during a HomeAssistant update (of all blinds). Hopefully that will make these EEPROM problems occur less often.
The PR is here: https://github.com/home-assistant/core/pull/75494

I am also in daily contact with the manufacturer and we are looking into ways of resolving these issues.

**Comment by wmollenvanger** [comment]
Got a new firmware from Brel (A1.08_B0.1.8) which is not (yet) an official one you can get via updates and it works again.

**Comment by starkillerOG** [comment]
@wmollenvanger good to hear it is working again for you!
Please let me know if the problem re-appears on the new firmware.

**Comment by EDelsman** [comment]
Is tere any news on this new firmware for Motion bridges? I and some one else still have these problems.

**Comment by starkillerOG** [comment]
@EDelsman so the problem comes from limited write capabality to the EEPROM.
The new firmware does not write to EEPROM anymore if the status has not changed from what is stored in cach.
This reduces EEPROM writes a lot and helps solve these issues.

I however do not know the current status of deployment of the new firmware.
I will ask the manufacturers.

**Comment by CrazyBird-HA** [comment]
Hi All, 

I'm looking at the same issue here.
Recently I had some DIAZ blinds installed and using HA via my Velbus installation.

It looks like I can read all information like battery status or open/close.
I'm using the DIAZ bridge, but got my AccessToken from the MotionBlinds App. As I couldn't find any in the DIAZ app.
Not sure if this is the one to use?
From other posts/issues I learned to do some tests with Python, but not getting any further then reading information.

So, some questions:

1. Do I need to have some Motion Blinds bridges and would they connect to my DIAZ blinds?
2. Is there more I can test or do to find out where my issue is located?
3. Is there anyone else using DIAZ blinds in HA. They are stated as worked at least once by someone. :)

Thanks for your responses!

**Comment by starkillerOG** [comment]
@CrazyBird-HA you need to use either a dedicated DIAZ app if it is available or the Connector app.
The MotionBlinds app will only work with Motionblinds devices.

You should be able to get the acces token form the DIAZ app/Connector app.

**Comment by quotary** [comment]
Not sure if you'd like a standalone report or pitching in on this thread is approved, but I'd like to add that I am having issues as described above.

From the HA logs:

First appearance: 23-04-2025 15:24:21 (155 times)
Last appearance: 24-04-2025 16:58:41

    Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20250424141837733', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'msgID': '20250424161835916', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
    Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20250424142838773', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'msgID': '20250424162836955', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
    Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20250424143839749', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'msgID': '20250424163837932', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
    Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20250424144840775', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'msgID': '20250424164838959', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'
    Received actionResult: 'AccessToken error', when sending message: '{'msgType': 'WriteDevice', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'AccessToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'msgID': '20250424145841783', 'data': {'operation': 5}}', got response: '{'msgType': 'WriteDeviceAck', 'mac': '78ee4c08a6b00001', 'deviceType': '10000000', 'msgID': '20250424165839968', 'token': 'xxxxxxxxxxxxxxxx', 'actionResult': 'AccessToken error'}'

Situation is as follows:
I'm using BREL rollershades and the BREL HUB-03 powered by POE (thus having a wired internet connection).
These rollershades and the hub have been installed yesterday (hence the first appearance 23-04-2025).

Hub firmware has been updated through the BREL app and is A1.1.0_B0.1.6. According to the app the latest version.
The API key has been retrieved through the BREL app. 

I can see the state and move it via the BREL app. 
I can see the state in HA and this updates nicely, but I can't move the rollershades via the BREL app.

I'm eager to help with troubleshooting if need be. Thanks in advance.
